import fs from 'node:fs';
import assert from 'node:assert/strict';
const handlers={};let latest;
globalThis.scrollY=0;globalThis.innerHeight=900;
globalThis.Element=class{};
globalThis.addEventListener=(name,fn)=>{handlers[name]=fn};
globalThis.matchMedia=()=>({matches:true});
globalThis.document={documentElement:{scrollHeight:5000},addEventListener:()=>{}};
globalThis.window={scrollTo:()=>{}};
globalThis.testReduced={matches:false,addEventListener:()=>{}};
globalThis.testSpring=()=>({on(){},jump(){},set(to){latest={to};}});
let code=fs.readFileSync(new URL('../src/wheel-scroll.js',import.meta.url),'utf8').replace(/import .*\n/g,'');
code='const springValue=globalThis.testSpring,reduced=globalThis.testReduced;\n'+code;
const {initWheelScroll}=await import('data:text/javascript,'+encodeURIComponent(code));initWheelScroll();
let prevented=false;
const wheel=(extra={})=>handlers.wheel({deltaX:0,deltaY:120,deltaMode:0,cancelable:true,target:null,preventDefault(){prevented=true},...extra});
wheel();assert.equal(latest.to,78);assert.ok(prevented);
wheel();assert.equal(latest.to,156);
wheel({deltaY:100000});assert.equal(latest.to,4100);
prevented=false;wheel({ctrlKey:true});assert.equal(prevented,false);
testReduced.matches=true;wheel();assert.equal(prevented,false);
console.log('Wheel accumulation, document boundary, zoom and reduced-motion checks passed.');
